# Generated by Django 4.2.30 on 2026-07-20 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('java', 'Java')], default='python', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('judging', 'Judging'), ('compile_error', 'Compilation Error'), ('graded', 'Graded')], default='queued', max_length=20)),
                ('score', models.FloatField(default=0.0, help_text='Total marks/score received')),
                ('compile_output', models.TextField(blank=True, help_text='Compiler or Interpreter output logs', null=True)),
                ('context_type', models.CharField(choices=[('exam', 'Exam'), ('practice', 'Practice'), ('standalone', 'Standalone')], default='standalone', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('coding_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='content.codingquestion')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='exams.exam')),
                ('practice_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='practice.practiceset')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_index', models.IntegerField(help_text='0-indexed position of the testcase in lists')),
                ('is_hidden', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Wrong Answer'), ('runtime_error', 'Runtime Error'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded')], max_length=30)),
                ('runtime_seconds', models.FloatField(default=0.0)),
                ('memory_bytes', models.IntegerField(default=0)),
                ('output_received', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_results', to='judge.submission')),
            ],
        ),
    ]
