# Generated by Django 4.2.30 on 2026-07-22 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_examcodingquestion_exammcqquestion_and_more'),
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='coding_question',
        ),
        migrations.AddField(
            model_name='submission',
            name='exam_coding_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='content.examcodingquestion'),
        ),
        migrations.AddField(
            model_name='submission',
            name='practice_coding_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='content.practicecodingquestion'),
        ),
    ]
