# Generated by Django 4.2.30 on 2026-07-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department_user_is_approved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='institution',
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='class',
            name='institution',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
