# Generated by Django 4.2.30 on 2026-07-20 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('solution_reveal_rule', models.CharField(choices=[('immediate', 'After First Attempt'), ('delayed', 'After N Attempts'), ('never', 'Never')], default='immediate', max_length=20)),
                ('reveal_after_n', models.IntegerField(default=1, help_text='Number of attempts before revealing solution (if delayed)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sets', to=settings.AUTH_USER_MODEL)),
                ('topics', models.ManyToManyField(help_text='Topics this practice set is built from', related_name='practice_sets', to='content.topic')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('mcq_score', models.FloatField(default=0.0)),
                ('coding_score', models.FloatField(default=0.0)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('practice_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='practice.practiceset')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSetClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_assignments', to='accounts.class')),
                ('practice_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='practice.practiceset')),
            ],
            options={
                'verbose_name_plural': 'Practice Set Class Assignments',
                'unique_together': {('practice_set', 'class_group')},
            },
        ),
    ]
