# Generated by Django 4.2.30 on 2026-07-24 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_practicecodingquestion_explanation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceset',
            name='reveal_after_n',
        ),
        migrations.AlterField(
            model_name='practiceset',
            name='solution_reveal_rule',
            field=models.CharField(choices=[('immediate', 'After First Attempt'), ('never', 'Never')], default='immediate', max_length=20),
        ),
        migrations.CreateModel(
            name='PracticeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('coding', 'Coding')], max_length=10)),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coding_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.practicecodingquestion')),
                ('mcq_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.practicemcqquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
