# Generated by Django 4.2.30 on 2026-09-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_remove_practiceset_reveal_after_n_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceset',
            name='is_randomized',
            field=models.BooleanField(default=False, help_text='Randomize question ordering for each student'),
        ),
    ]
