# Generated by Django 4.2.30 on 2026-07-20 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(help_text='A list of option strings')),
                ('correct_option_index', models.IntegerField(help_text='0-indexed index of correct option')),
                ('explanation', models.TextField(blank=True, null=True)),
                ('marks', models.IntegerField(default=1)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list, help_text='A list of tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='content.topic')),
            ],
        ),
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('input_format', models.TextField()),
                ('output_format', models.TextField()),
                ('sample_test_cases', models.JSONField(help_text="List of dicts with 'input' and 'output'")),
                ('hidden_test_cases', models.JSONField(help_text="List of dicts with 'input' and 'output'")),
                ('starter_code', models.TextField(blank=True, null=True)),
                ('time_limit', models.FloatField(default=1.0, help_text='Time limit in seconds')),
                ('memory_limit', models.IntegerField(default=256, help_text='Memory limit in MB')),
                ('marks', models.IntegerField(default=5)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list, help_text='A list of tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_questions', to='content.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicClassVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visible_topics', to='accounts.class')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibilities', to='content.topic')),
            ],
            options={
                'verbose_name_plural': 'Topic Class Visibilities',
                'unique_together': {('topic', 'class_group')},
            },
        ),
    ]
