# Generated by Django 4.2.30 on 2026-07-22 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_examcodingquestion_exammcqquestion_and_more'),
        ('judge', '0002_remove_submission_coding_question_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodingQuestion',
        ),
        migrations.DeleteModel(
            name='MCQQuestion',
        ),
        migrations.AddField(
            model_name='practicemcqquestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_mcq_questions', to='content.topic'),
        ),
        migrations.AddField(
            model_name='practicecodingquestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_coding_questions', to='content.topic'),
        ),
        migrations.AddField(
            model_name='exammcqquestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_mcq_questions', to='content.topic'),
        ),
        migrations.AddField(
            model_name='examcodingquestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_coding_questions', to='content.topic'),
        ),
    ]
