# Generated by Django 4.2.30 on 2026-07-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_delete_codingquestion_delete_mcqquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicecodingquestion',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
