# Generated by Django 4.2.30 on 2026-07-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_practicecodingquestion_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='purpose',
            field=models.CharField(choices=[('exam', 'Exam'), ('practice', 'Practice'), ('both', 'Both')], default='both', max_length=20),
        ),
    ]
